apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-with-secret
  name: nginx-with-secret
  namespace: workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-with-secret
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-with-secret
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        # THIS IS HOW SECRETS ARE ADDED
        volumeMounts:
        - name: my-secret
          mountPath: /etc/my-secret
          readOnly: true
      
      volumes:
      - name: my-secret
        secret:
          secretName: my-secret
          
status: {}
