apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echoserver
  name: echoserver
  namespace: external
spec:
  ports:
  - name: 5005-8080
    port: 5005
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver
  type: ClusterIP
status:
  loadBalancer: {}
