apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echoserver
  name: echoserver
  namespace: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echoserver
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.10
        name: echoserver
        ports:
        - containerPort: 8080
        resources: {}
status: {}
