apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-server
  name: echo-server
  namespace: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-server
    spec:
      containers:
      - image: echo-server
        name: echo-server
        resources: {}
status: {}
