apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echoserver
  name: echoserver
  namespace: external
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver
status:
  loadBalancer: {}
