apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: storage
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - mountPath: "/var/log/nginx"
      name: my-volume

  # Volumes 
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
