apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: storage
spec:
  # PVC with its storageClassName set equal 
  # to "" is always interpreted to be requesting 
  # a PV with no class, so it can only be bound to PVs with no class
  storageClassName: ""
  # has to be capacity.storage
  capacity:
    storage: 1Gi
  # this is required
  accessModes:
  - ReadWriteOnce
  # this is required
  hostPath:
    path: /tmp/logs
